### ISSUE TITLE
DU2.ipynb

### ISSUE THREAD

**Issue by KaterinaJanotova** [KaterinaJanotova/pythonproDS#2]
Tak a vůbec nevím jestli jsem to nahrála úspěšně :-)

**Comment by KaterinaJanotova** [comment]
Tak asi nahrala, ale do vetve master

**Comment by vaclavcepelak** [comment]
Ahoj Katko, dobrá práce! Všechno funguje, jak má, takže úkol je splněn. Jsou tam dvě zásadnější věci
- chybí ti tam StandardScaler. A zároveň to není chyba, protože v tomhle případě zrovna není potřeba - věděla bys proč?

Nechci tě tím už zatěžovat, úkol je splněn (zadáno do tabulky). V rámci sekce "rady do života" přidávám pár formálních věcí:
- Je dobré nemít v tom notebooku importy, které pak nepoužíváš. VS Code ti je barevně odliší.
- Jirka psal, ať využiješ výchozí metodu decision_function_shape "ovo", nicméně dle dokumentace se výchozí metoda změnila na "ovr", čili bych pro jistotu doporučoval to přeci jen nastavit (s různou verzí knihovny by se to mohlo měnit). Ale na výsledek to nemá vliv.
- Doporučuju přidat komentáře a zadání (případně odkaz na kompletní zadání)

Pokud bys chtěla sjednotit ty větve, můžeš postupovat takto:
- Otevři si repository ve VS Code
- Otevři si terminál
- Dej `git pull` - stáhnout se ti všechny změny z githubu k tobě na lokál (=na počítač)
- Dej `git checkout master` - dostaneš se do větve master
- Soubor s druhým úkolem si zkopíruj někam vedle
- Dej `git checkout main` - dostaneš se do větve master
- Soubor s druhým úkolem ti zmizel, tak si ho zkopíruj zpátky
- Přidej soubor, commitni a pushni (to už nejspíš znáš - doporučuji přímo přes VS Code)
- Jakmile ověříš, že je vše ve správné větvi na githubu, můžeš větev `master` smazat
- git push origin --delete master (smaže na githubu)
- git branch -D master (smaže u tebe na lokálu/na počítači)

Přeju hodně štěstí v práci s daty a i jinak!

V.
